### DISCUSSION TITLE
My docker-compose.yml

### DISCUSSION THREAD

**Discussion by Pipboyguy** [abetlen/llama-cpp-python#239] [Show and tell]
I use this setup for integration with vectorstore:

```yaml
---
version: "3.9"
services:
  docstore:
    image: qdrant/qdrant:dev
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant:/qdrant/storage
      - ./qdrant_config.yaml:/qdrant/config/production.yaml
  llama_server:
    build: 
      context: "https://github.com/abetlen/llama-cpp-python.git#main"
      dockerfile: Dockerfile.cuda
      args:
        CUDA_VERSION: ${CUDA_VERSION}
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - llama_server.env
    depends_on:
      - docstore
volumes:
  qdrant: {}

```
