### ISSUE TITLE
Problems when i try to use this inside the default python 3.10 docker container

### ISSUE THREAD

**Issue by LLukas22** [abetlen/llama-cpp-python#70]
When i try to install and use this package via a requirements file in the default 3.10 python container i get the following error when i try to import the module:
`Failed to load shared library '/usr/local/lib/python3.10/site-packages/llama_cpp/libllama.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.29' not found (required by /usr/local/lib/python3.10/site-packages/llama_cpp/libllama.so)`

Am i doing something wrong? Or am i just missing some dependencies?

**Comment by abetlen** [comment]
Do you mind posting the Dockerfile? I haven't tried to use this inside a container but I'l investigate.

**Comment by LLukas22** [comment]
Alright i cant send you the Dockerfile, but i created a toy-example with your own server.

Dockerfile:
```
FROM python:3.10

#install
RUN pip3 install llama-cpp-python[server]

#Expose the ports
EXPOSE 8000

# Make a Dir for the models to be mounted into
RUN mkdir -p /var/lib/models

#Set environment 
ENV MODEL "/var/lib/models/ggjt-model.bin"

#Start server
CMD ["python3","-m","llama_cpp.server"]
```

I then started the container via this docker-compose file:
```
version: "3.9"
services:
 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: llama-server
    container_name: llama-server

    ports:
      - "8000:8000"

    volumes:
      - [MODEL_DIR]:/var/lib/models
```

When running this the 'GLIBCXX_3.4.29' error is gone, but the model loads for a very long time and the container gets OOM killed sometimes. I'm running on 64GB so that's very strange. The other thing i noticed is that the container fails to bind the address but that's just docker IPv4 shenanigans. I will try to use llama-cpp-python[server] as a dependency in my other project and see  if it will get rid of the 'GLIBCXX_3.4.29' error.
