### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version - (Utlizing T4 GPU for llama cpp inference on a docker based setup)

### ISSUE THREAD

**Issue by talhalatifkhan** [abetlen/llama-cpp-python#763]
**Issue**

I am trying to utilize GPU for my inference but i am running into an issue with _**CUDA driver version is insufficient for CUDA runtime version**_. I have tried to change the cuda toolkit version use different base images but nothing seems to work.
```
web  | CUDA error 35 at /tmp/pip-install-iu4nd6_y/llama-cpp-python_ea6f0cbd4f6343bcbd9b3fd180bbd240/vendor/llama.cpp/ggml-cuda.cu:5522: CUDA driver version is insufficient for CUDA runtime version
web  | current device: 32643
```

I am using a spot instance on with T4 GPU. 

**nvcc version on host**
```
user@gpu-inst:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```
**nvcc version in container**
```
root@af3d8458b74f:/src# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```

**Docker file that i am using**

```
ARG CUDA_IMAGE="12.2.0-devel-ubuntu22.04"
FROM nvidia/cuda:${CUDA_IMAGE}

# Set the working directory
WORKDIR /src

COPY requirements.txt .

# setting build related env vars
ENV CUDA_DOCKER_ARCH=all
ENV LLAMA_CUBLAS=1
ENV DEBIAN_FRONTEND=noninteractive

# Install Python 3 and pip

RUN apt-get update \
    && apt-get install -y curl wget gnupg cmake git lsb-release build-essential dumb-init \
    python3 \
    python3-pip \
    && pip install --upgrade pip \
    && wget -qO- https://github.com/jwilder/dockerize/releases/download/v0.7.0/dockerize-alpine-linux-amd64-v0.7.0.tar.gz | tar xvz -C /usr/local/bin \
    && pip install -r requirements.txt

# Install llama-cpp-python (build with cuda)
RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --no-cache-dir

# Copy the app source code
COPY . /src

RUN chmod 755 /src/scripts/dev.sh

ENV PYTHONPATH=/src

ENTRYPOINT ["dumb-init", "--"]

CMD ["/bin/bash", "-c", "/src/scripts/dev.sh"]


```

**Docker compose file**

```
version: '3.9'

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    ports:
      - "80:80"
    depends_on:
      - scylla_db
    volumes:
      - ./app:/src/app
      - ./cache:/src/cache
    networks:
      cloud:
```
