### ISSUE TITLE
deepseek chat_format template

### ISSUE THREAD

**Issue by mjwweb** [abetlen/llama-cpp-python#969]
**Is your feature request related to a problem? Please describe.**
Request for a deepseek chat_format template

**Additional context**
Deepseek prompt template found here: 
https://huggingface.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF

```
You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer.
### Instruction:
{prompt}
### Response:
```

**Comment by tastypear** [comment]
Perhaps the chat_format templates should be stored in a configuration file.

In this way, users can edit the .conf to adapt to any model without changing the code.

**Comment by tastypear** [comment]
@mjwweb I have added `--chat-format` to the `llama.cpp/examples/server/api_like_OAI.py`(not llama.cpp-python) --> [my repo](https://github.com/tastypear/llama-cpp-oai-like-server)
You can edit `chat-format.toml` to add your template.

For deepseek-coder-instruct, maybe like this:
```toml
[deepseek-coder-instruct]
prefix = "You are an AI programming assistant.\n"
system = ""
user = "### Instruction:{content}\n"
assistant = "### Response:{content}\n"
suffix = "### Response:"
```

then run:
`./server -m model.gguf` and
`python api_like_OAI.py --chat-format deepseek-coder-instruct`

I haven't tested this template myself, but it should be easy to adjust to make it work.
